
# Documentation image
image=docs/docker.github.io:latest
# Container name
container=docker-docs
# File to store the image
tarfile=docker-docs-image.tar

port_map=8081:4000

include ../Makefile

create:	docs-create
rm: docs-rm

start: docs-start
stop: docs-stop

save: docs-save
load: docs-load

logs: docs-logs

pull: docs-pull
